<a href="https://colab.research.google.com/github/mohit-kumar396/SQL-Practice/blob/main/SQL_Join.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import sqlite3
customers_df=pd.read_csv("customers.csv")
orders_df=pd.read_csv("orders.csv")
conn=sqlite3.connect(":memory:")

In [3]:
customers_df.to_sql("customers", conn,index=False, if_exists="replace")
orders_df.to_sql("orders", conn,index=False, if_exists="replace")
# Above line ka meaning:- "Take the Pandas DataFrame df and store it as an SQL
# table named orders inside the database conn."

12

In [4]:
query1="""
select * from  orders
"""
result=pd.read_sql(query1,conn)
result

    order_id  customer_id     product  amount
0          1          101      Laptop   55000
1          2          103       Mouse     800
2          3          101    Keyboard    1500
3          4          105     Monitor   12000
4          5          102      Laptop   52000
5          6          107  Headphones    2500
6          7          110       Mouse     900
7          8          103      Laptop   58000
8          9          108    Keyboard    1800
9         10          105       Mouse     850
10        11          109     Monitor   11000
11        12          103  Headphones    3000

In [5]:
query2="""
select product, amount from orders where customer_id=101 or customer_id=103
"""
result=pd.read_sql(query2,conn)
result

      product  amount
0      Laptop   55000
1       Mouse     800
2    Keyboard    1500
3      Laptop   58000
4  Headphones    3000

In [6]:
query3="""
select * from  customers
"""
result=pd.read_sql(query3,conn)
result

   customer_id customer_name      city
0          101          Amit     Delhi
1          102          Riya  Guwahati
2          103         Mohit     Patna
3          104          Neha   Kolkata
4          105         Rahul     Delhi
5          106         Priya   Silchar
6          107         Arjun     Patna
7          108         Sneha  Guwahati
8          109         Vikas   Kolkata
9          110        Anjali     Delhi

In [7]:
#Lets Read Join

In [8]:
# 1. Inner Join

In [9]:
query4="""
select customers.customer_name, customers.city, orders.product, orders.amount
from customers inner join orders on customers.customer_id=orders.customer_id
"""
result=pd.read_sql(query4,conn)
result

   customer_name      city     product  amount
0           Amit     Delhi    Keyboard    1500
1           Amit     Delhi      Laptop   55000
2           Riya  Guwahati      Laptop   52000
3          Mohit     Patna  Headphones    3000
4          Mohit     Patna      Laptop   58000
5          Mohit     Patna       Mouse     800
6          Rahul     Delhi     Monitor   12000
7          Rahul     Delhi       Mouse     850
8          Arjun     Patna  Headphones    2500
9          Sneha  Guwahati    Keyboard    1800
10         Vikas   Kolkata     Monitor   11000
11        Anjali     Delhi       Mouse     900

#**Left Join**

In [10]:
query5="""
select customers.customer_name, customers.city, orders.product, orders.amount
from customers left join orders on customers.customer_id=orders.customer_id
"""
result=pd.read_sql(query5,conn)
result

   customer_name      city     product   amount
0           Amit     Delhi    Keyboard   1500.0
1           Amit     Delhi      Laptop  55000.0
2           Riya  Guwahati      Laptop  52000.0
3          Mohit     Patna  Headphones   3000.0
4          Mohit     Patna      Laptop  58000.0
5          Mohit     Patna       Mouse    800.0
6           Neha   Kolkata        None      NaN
7          Rahul     Delhi     Monitor  12000.0
8          Rahul     Delhi       Mouse    850.0
9          Priya   Silchar        None      NaN
10         Arjun     Patna  Headphones   2500.0
11         Sneha  Guwahati    Keyboard   1800.0
12         Vikas   Kolkata     Monitor  11000.0
13        Anjali     Delhi       Mouse    900.0

In [11]:
query6="""
select customers.customer_name, customers.city, orders.product, orders.amount
from customers left join orders on customers.customer_id=orders.customer_id
"""
result=pd.read_sql(query6,conn)
result

   customer_name      city     product   amount
0           Amit     Delhi    Keyboard   1500.0
1           Amit     Delhi      Laptop  55000.0
2           Riya  Guwahati      Laptop  52000.0
3          Mohit     Patna  Headphones   3000.0
4          Mohit     Patna      Laptop  58000.0
5          Mohit     Patna       Mouse    800.0
6           Neha   Kolkata        None      NaN
7          Rahul     Delhi     Monitor  12000.0
8          Rahul     Delhi       Mouse    850.0
9          Priya   Silchar        None      NaN
10         Arjun     Patna  Headphones   2500.0
11         Sneha  Guwahati    Keyboard   1800.0
12         Vikas   Kolkata     Monitor  11000.0
13        Anjali     Delhi       Mouse    900.0

#**Right Join:-  returns all rows from the right table (table2), and only the matched rows from the left table (table1).**

In [12]:
# iss query ko left join ko reverse kar kk likha hai bcz right join and full join sqlite me suppoert nhi karta.
query7="""
select customers.customer_name, customers.city, orders.product, orders.amount
from orders left join customers on customers.customer_id=orders.customer_id
"""
result=pd.read_sql(query7,conn)
result

   customer_name      city     product  amount
0           Amit     Delhi      Laptop   55000
1          Mohit     Patna       Mouse     800
2           Amit     Delhi    Keyboard    1500
3          Rahul     Delhi     Monitor   12000
4           Riya  Guwahati      Laptop   52000
5          Arjun     Patna  Headphones    2500
6         Anjali     Delhi       Mouse     900
7          Mohit     Patna      Laptop   58000
8          Sneha  Guwahati    Keyboard    1800
9          Rahul     Delhi       Mouse     850
10         Vikas   Kolkata     Monitor   11000
11         Mohit     Patna  Headphones    3000

#**Full join:- Since Full join is not supported in sqlite so we will do union of left join and right join(reversed left join)**

In [13]:
query8="""
select customers.customer_name, customers.city, orders.product, orders.amount
from customers left join orders on customers.customer_id=orders.customer_id
union
select customers.customer_name, customers.city, orders.product, orders.amount
from orders left join customers on customers.customer_id=orders.customer_id
"""
result=pd.read_sql(query8,conn)
result

   customer_name      city     product   amount
0           Amit     Delhi    Keyboard   1500.0
1           Amit     Delhi      Laptop  55000.0
2         Anjali     Delhi       Mouse    900.0
3          Arjun     Patna  Headphones   2500.0
4          Mohit     Patna  Headphones   3000.0
5          Mohit     Patna      Laptop  58000.0
6          Mohit     Patna       Mouse    800.0
7           Neha   Kolkata        None      NaN
8          Priya   Silchar        None      NaN
9          Rahul     Delhi     Monitor  12000.0
10         Rahul     Delhi       Mouse    850.0
11          Riya  Guwahati      Laptop  52000.0
12         Sneha  Guwahati    Keyboard   1800.0
13         Vikas   Kolkata     Monitor  11000.0