<a href="https://colab.research.google.com/github/mohit-kumar396/SQL-Practice/blob/main/Sql_Ramakrishnan_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [2]:
#Sailors Table:-
cursor.execute("""
create table Sailors(
sid integer,
sname string,
rating integer,
age real
)
""")

In [3]:
# Boats Table:-
cursor.execute("""
create table Boats(
bid integer,
bname string,
color string
)
""")

In [4]:
# Reserves Table:-
cursor.execute("""
create table Reserves(
sid integer,
bid integer,
day date
)
""")

In [5]:
# Value fill in sailors table:-
cursor.execute("""
insert into Sailors values
(22,'dustin',7,45.0),
(29, 'Brutus', 1, 33.0),
(31, 'Lubber', 8, 55.0),
(32, 'Andy', 8, 25.5),
(58, 'Rusty', 10, 35.0),
(64, 'Horatio', 7, 35.0),
(71, 'Zorba', 10, 16.0),
(74, 'Horatio', 9, 35.0),
(85, 'Art', 3, 25.5),
(95, 'Bob', 3, 63.5)
""")
conn.commit()

In [6]:
# Value Fill in Boats table:-
cursor.execute("""
insert into Boats values
(101, 'Interlake', 'blue'),
(102, 'Interlake', 'red'),
(103, 'Clipper', 'green'),
(104, 'Marine', 'red')
""")
conn.commit

In [7]:
# Values Fill in Reserves Table:-
cursor.execute("""
insert into Reserves values
(22, 101, '10/10/98'),
(22, 102, '10/10/98'),
(22, 103, '10/8/98'),
(22, 104, '10/7/98'),
(31, 102, '11/10/98'),
(31, 103, '11/6/98'),
(31, 104, '11/12/98'),
(64, 101, '9/5/98'),
(64, 102, '9/8/98'),
(74, 103, '9/8/98')
""")
conn.commit()

In [8]:
# Lets start Querying

In [9]:
# Q1:- Find the'names and ages ofall sailors.

In [10]:
query1="""
select distinct S.sname, S.age from sailors S
"""
result=pd.read_sql_query(query1,conn)
result

     sname   age
0   dustin  45.0
1   Brutus  33.0
2   Lubber  55.0
3     Andy  25.5
4    Rusty  35.0
5  Horatio  35.0
6    Zorba  16.0
7      Art  25.5
8      Bob  63.5

In [11]:
#Q2:-Find all sailors from with a rating above 7

In [12]:
query2="""
select * from Sailors S where s.rating>7
"""
result=pd.read_sql_query(query2,conn)
result

   sid    sname  rating   age
0   31   Lubber       8  55.0
1   32     Andy       8  25.5
2   58    Rusty      10  35.0
3   71    Zorba      10  16.0
4   74  Horatio       9  35.0

In [13]:
# Q.3:- Find the names of sailors 'Who have reseTved boat number 103

In [14]:
query3="""
select S.sname from Sailors S , Reserves R where S.sid=R.sid and R.bid=103
"""
result=pd.read_sql_query(query3,conn)
result

     sname
0   dustin
1   Lubber
2  Horatio

In [15]:
#Q.4:- Find sids of Sailors who have reserved a red boat:-

In [16]:
query4="""
select S.sid, S.sname, B.color from Sailors S, Reserves R, Boats B where S.sid=R.sid and B.bid=R.bid and B.color='red'
"""
result=pd.read_sql_query(query4,conn)
result

   sid    sname color
0   22   dustin   red
1   31   Lubber   red
2   64  Horatio   red
3   22   dustin   red
4   31   Lubber   red

In [17]:
# Q5:- Find the color of boats reserved by Lubber.

In [18]:
query5="""
select B.color from Sailors S, Reserves R, Boats B where S.sid=R.sid and B.bid=R.bid and S.sname='Lubber'
"""
result=pd.read_sql_query(query5,conn)
result

   color
0    red
1  green
2    red

In [19]:
#Q.6:- Find the names of sailors who have reserved at least one boat.

In [20]:
query6="""
select S.sname from Sailors S, Reserves R where S.sid=R.sid
"""
result=pd.read_sql_query(query6,conn)
result

     sname
0   dustin
1   dustin
2   dustin
3   dustin
4   Lubber
5   Lubber
6   Lubber
7  Horatio
8  Horatio
9  Horatio

In [21]:
# Q7:- Find the ages of sailors whose name begins and ends with B and has at least three chamcters.

In [22]:
query7="""
select S.sname, S.age from Sailors S where S.sname like 'B%b'
"""
result=pd.read_sql_query(query7,conn)
result

  sname   age
0   Bob  63.5

In [23]:
# Note:- wild card _ means exactly one character.
# Note:- wild card _ means 0 or more character.

In [24]:
# Q8 :- Find the name of sailors who have reserved a red boat or green boat.

In [25]:
query8="""
select S.sname from Sailors S, Reserves R, Boats B where S.sid=R.sid and B.bid=R.bid and (B.color='red' or B.color='green')
"""
result=pd.read_sql_query(query8,conn)
result
# For this question you can use union also.

     sname
0   dustin
1   Lubber
2  Horatio
3   dustin
4   Lubber
5  Horatio
6   dustin
7   Lubber

In [26]:
# Q8 :- Find the name of sailors who have reserved a red boat and green boat.
# Ans:- same as above the change is "or" is there and "and" will be here in place of "or"

In [27]:
# Q9 :- Find the sids of all sailor's who have reserved red boats but not green boats.

In [28]:
query9="""
select S.sid from Sailors S, Reserves R, Boats B where S.sid=R.sid and B.bid=R.bid and B.color='red' and not B.color='green'
"""
result=pd.read_sql_query(query9,conn)
result
# for this question you can use except also

   sid
0   22
1   31
2   64
3   22
4   31

In [29]:
# Q10:-  Find all sids of sailors who have a rating of 10 or reserved boat 104.

In [30]:
query10="""
select distinct S.sid from Sailors S, Reserves R where S.rating=10 or (S.sid=R.sid and R.bid=104)
"""
result=pd.read_sql_query(query10,conn)
result
# here distinct is used to avoid duplicate sids bcz there is sailors and reserves tables so cross product will be there.

   sid
0   22
1   31
2   58
3   71

In [31]:
# Nested Queries:-

In [32]:
# Q11:- Using IN Find the names of sailors who have reserved boat 103.

In [33]:
query11="""
select S.sname from Sailors S where S.sid in (select R.sid from Reserves R where R.bid=103)
"""
result=pd.read_sql_query(query11,conn)
result

     sname
0   dustin
1   Lubber
2  Horatio

In [34]:
# Q12:- Using IN  Find the names of sailors who have reserved red boat.

In [35]:
query12="""
select S.sname from Sailors S where S.sid in (select R.sid from Reserves R where R.bid in
(select B.bid from Boats B where B.color='red'))
"""
result=pd.read_sql_query(query12,conn)
result

     sname
0   dustin
1   Lubber
2  Horatio

In [36]:
# Q13:-  Using IN  Find the names of sailors who have not reserved a red boat.

In [37]:
query13="""
select S.sname from Sailors S where S.sid not in (select R.sid from Reserves R where R.bid in
(select B.bid from Boats B where B.color ='red'))
"""
result=pd.read_sql_query(query13,conn)
result

     sname
0   Brutus
1     Andy
2    Rusty
3    Zorba
4  Horatio
5      Art
6      Bob

In [38]:
# Q14. Find sailors whose rating is better than some sailor called Horatio.

In [39]:
query14 = """
select s1.sid from Sailors s1 where s1.rating > (select min(s2.rating) from Sailors s2 where s2.sname = 'Horatio')
"""
result = pd.read_sql_query(query14, conn)
result

   sid
0   31
1   32
2   58
3   71
4   74

In [40]:
# Q15. Find sailors whose rating is better than every sailor' called Horat·to.

In [41]:
query15="""
select s1.sname from Sailors s1 where s1.rating > (select max(s2.rating) from Sailors s2 where s2.sname='Horatio')
"""
result=pd.read_sql_query(query15,conn)
result

   sname
0  Rusty
1  Zorba

In [42]:
# Note:- Useful operators like in

In [43]:
# 1. Comparison Operators
#    - =, <>, !=, >, <, >=, <=

# 2. Logical Operators
#    - AND, OR, NOT

# 3. Membership Operators
#    - IN, NOT IN

# 4. Range Operator
#    - BETWEEN

# 5. Pattern Matching
#    - LIKE

# 6. NULL Operators
#    - IS NULL, IS NOT NULL

# 7. Existence Operator
#    - EXISTS

# 8. Subquery Operators
#    - ANY / SOME
#    - ALL

# 9. Arithmetic Operators
#    - +, -, *, /, %

In [44]:
# Q16. Find the sailor's with the highest rating

In [45]:
query16="""
select s.sname from Sailors s where s.rating >= (select max(s1.rating) from Sailors s1)
"""
result=pd.read_sql_query(query16,conn)
result

   sname
0  Rusty
1  Zorba

In [46]:
# Q17. Find the names of sailors who have reserved botha red anda green boat

In [47]:
query17="""
select s.sname from Sailors s where s.sid in
(select r1.sid from Reserves r1 where r1.bid in
(select b1.bid from Boats b1 where b1.color='red'))
intersect
select s1.sname from Sailors s1 where s1.sid in
(select r2.sid from Reserves r2 where r2.bid in
(select b2.bid from Boats b2 where b2.color='green'))
"""
result=pd.read_sql_query(query17,conn)
result

     sname
0  Horatio
1   Lubber
2   dustin

In [48]:
# Q18.  Find the names of sailors who have reserved both a red anda green boat

In [49]:
query18="""select S.sname from Sailors S where S.sid in
 (select R.sid from Reserves R, Boats B where R.bid=B.bid and B.color="red"
 intersect
 select R1.sid from Reserves R1, Boats B1 where R1.bid=B1.bid and B1.color="green")
"""
result=pd.read_sql_query(query18,conn)
result

    sname
0  dustin
1  Lubber

In [50]:
#  Q19. Find the names of sailors who are older than the oldest sailor with a rating of 10.

In [51]:
query19="""
select S.sname from Sailors S where S.age > (select max(S1.age) from Sailors S1 where S1.rating=10)
"""
result=pd.read_sql_query(query19,conn)
result

    sname
0  dustin
1  Lubber
2     Bob

In [52]:
# Q20. For each red boat, find no of reservation for this boat.

In [53]:
query20="""
select B.bid, count(*) as Reservation_count from Boats B, Reserves R where B.bid=R.bid and B.color='red' group by B.bid
"""
result=pd.read_sql_query(query20,conn)
result

   bid  count(*)
0  102         3
1  104         2

In [54]:
# Q21. Find the average age of sailors for each rating level that has at least two sailors.

In [57]:
query20="""
select S.rating, avg(S.age) as Average_age from Sailors S group by S.rating having count(*)>1
"""
result=pd.read_sql_query(query20,conn)
result

   rating  Average_age
0       3        44.50
1       7        40.00
2       8        40.25
3      10        25.50

In [58]:
# Q22.  Find the average age of sailors who is eligible to vote (i.e., at least 18years old)
#  for each rating level that has at least two such sailors

In [60]:
query22="""
select S.rating,  avg(S.age) as Average_age from Sailors S where S.age>=18 group by S.rating having count(*)>1
"""
result=pd.read_sql_query(query22,conn)
result

   rating  Average_age
0       3        44.50
1       7        40.00
2       8        40.25

In [61]:
# Doubt. Q23. Find those ratings for which average age of sailor is minimum over all ratings.

In [63]:
query23="""
SELECT rating, avgage
FROM (
    SELECT S.rating, AVG(S.age) AS avgage
    FROM Sailors S
    GROUP BY S.rating
)
WHERE avgage = (
    SELECT MIN(avgage)
    FROM (
        SELECT AVG(S.age) AS avgage
        FROM Sailors S
        GROUP BY S.rating
    )
);
"""
result=pd.read_sql_query(query23,conn)
result

   rating  avgage
0      10    25.5